### ISSUE TITLE
3DH transcript is incomplete

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#108]
The 3DH transcript used in the key schedule [currently includes only the nonces and identity](https://cfrg.github.io/draft-irtf-cfrg-opaque/draft-irtf-cfrg-opaque.html#section-4.2.2.2). This means the contents of info1, info2, and the core OPAQUE messages are not mixed into encryption or MAC keys, which seems less than idea. They are included in the transcript that is covered by the MAC, but I don't see why wouldn't *also* include them in the key schedule. 

@hugokraw, can this be improved?

**Comment by hugokraw** [comment]
The protocol is secure as defined. Adding more elements to the key derivation does not hurt, even if not strictly necessary, but omitting elements is insecure. In particular, including the transcript instead of the currently defined info, may not include identities as these may not be appear in the transcript (are idU and idS necessarily transmitted explicitly as part of the transcript?) and identities are needed in the derivation.
You could just add a transcript element to the key derivation in addition to "info". In this case, the derivation of SK could use transcript3 as currently defined, but the derivation of handshake_secret cannot use transcript2. It will need to define a new value transcript2' that stops before Einfo2. 
I am not sure the extra complexity is worth given that the simpler derivation suffices here.

Typo: The elements marked with * in the protocol description to indicate that they are optional appear as _ in the published draft (e.g., info1_)

**Comment by kevinlewi** [comment]
Can we close this issue? @chris-wood

**Comment by chris-wood** [comment]
I don't think so. It's quite inconsistent that the transcript used for key confirmation is not that which is used for key derivation. We should unify these two, as has been done in TLS 1.3. I'll use this issue to track that.

**Comment by hugokraw** [comment]
Session id's (nonces in this case) and identities is all you need as input to the key derivation. As I answered before, I am ok with adding transcript to the derivation mainly to avoid these questions, but it does not have a real cryptographic function once you authenticate the transcript during the handshake. If you add the transcript you may remove the nonces from info as they are part of the transcript, but you need to keep the identities (in addition to the transcript) which may not be part of the transcript.

**Comment by chris-wood** [comment]
Right, I understand that these are necessary, but it's awkward (from a protocol perspective) to omit everything else that's actually sent over the wire. We should follow best practice here, which is to fold as much into the transcript and key schedule as possible.

**Comment by hugokraw** [comment]
Where is the elegance of simplicity? Ok. Add the transcript but keep the identities as explicit entries, in addition to the transcript.

**Comment by chris-wood** [comment]
My claim is that it's less elegant as-is. The proposal allows clients and servers to only keep a running hash that includes the identifies and transcript processed so far. In contrast, the current text requires endpoints to do special processing of the KE messages to extract the nonces. It's more complex in practice.

**Comment by hugokraw** [comment]
I agree with this. Elegance and aestethics are contextual and in the eye of the beholder. And, you are right, the running hash is the right way to go. When all the fog of these changes dissipates, I'll have to take a comprehensive look at the specification. Right now, I see parts and pieces and not the whole picture.
