### ISSUE TITLE
Remove optional fields from 3DH

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#109]
The 3DH instantiation currently allows servers to send plaintext info in the second message, clients to send plaintext info in the third message, and clients to send encrypted info in the third message. This seems like too many options. In particular:

1. Since there is no cryptographic algorithm negotiation as part of the protocol, the primary benefit of info2 is to avoid server encryption in the second flight. This means that applications need to make a determination about what data is sensitive or not. (Servers already have the encryption keys at this point, so they can send anything they need encrypted and avoid giving applications an option.)
2. Clients have the encryption keys necessary to encrypt application info in the third message. Similar to (1), this means applications must make a choice about what data is sensitive. Removing that choice, by folding info3 into einfo3, simplifies things. 
3. Sending application info in the third flight does not make much sense to me in general. If clients need to send info in the third flight, it can be encrypted using keys derived from the output of OPAQUE, i.e., the main traffic secret `SK`, rather than keys derived from `handshake_secret`. I can't think of an example where a client would want to send data in the third flight that MUST be processed before the key confirmation message.

Based on the above, I think we should do the following: remove `info2`, `info3`, and `einfo3` from the protocol. `info1` and `einfo2` are sufficient for clients and servers to safely exchange application info as a preamble to the traffic secret, and all other info can be sent, encrypted, under a key derived from SK. 

@hugokraw, @kevinlewi, what do you think?

**Comment by kevinlewi** [comment]
I am all for this! Especially if there is no decrease in security.

**Comment by hugokraw** [comment]
I am ok with removing info2 and info3. I would leave einfo3 as there is no security decision to make here. If you are in a setting that requires sending something in the third flow, you use it. If there is no need for it, you don't. So the decision is a purely functional one, not security related. I find it hard to say that no reasonable application will need to use einfo3, , in particular, given that it is the first place where the client can communicate encrypted information to the server.

**Comment by chris-wood** [comment]
> I find it hard to say that no reasonable application will need to use einfo3, , in particular, given that it is the first place where the client can communicate encrypted information to the server.

My claim is that an application which needs to send info in the third message can send it encrypted with a key derived from SK, not from a handshake secret. This means there's effectively two ways to send information in the third flight -- either in einfo3 or in application data -- and it seems simpler to just force applications to use application data.

**Comment by hugokraw** [comment]
Kevin, didn't one of your applications used the key as a token rather than to encrypt data as soon as the handshake was done? That would be an example of an application that could use einfo3 (which may or may not be Kevin's case but still a reasonable one).

**Comment by kevinlewi** [comment]
@hugokraw, the application I had in mind relied on the *server encrypting data to the client*, using the shared secret established at the end of the key exchange. einfo3 is used for data being sent from client to server.

But, to clarify the original question: Right now, the draft says to compute:
```
Ke3 = HKDF-Expand-Label(handshake_secret, "client enc", "", key_length)
```
and use Ke3 as the encryption key for encrypting einfo3. What I would like to understand is: why do we need to derive this encryption key in this manner; why not just rely on using the shared secret as the encryption key instead?

If there are no *security concerns* with doing so, then we would like to remove einfo3 from the specification and defer it to the wrapper protocol that calls OPAQUE, since the wrapper protocol will have access to the shared secret and can choose to encrypt whatever equivalent of einfo3 it wishes.

**Comment by hugokraw** [comment]
I assume that by shared secret you mean SK. In that case, anything encrypted under SK must be considered application data and nothing that upon which the server will decide to establish the key or authenticate the client. The encrypted information SHALL NOT be part of the key exchange, If it is part of the key exchange then it needs to be sent in the clear or encrypted under Ke3 (otherwise you break the essential indistinguishability property of the key exchange). 
I was thinking of an application where the shared key SK is not intended for use  immediately at the end of the key exchange but later as some form of token  (in which case you may not want SK to be used immediately after the key exchange).

**Comment by chris-wood** [comment]
> I was thinking of an application where the shared key SK is not intended for use immediately at the end of the key exchange but later as some form of token (in which case you may not want SK to be used immediately after the key exchange).

Hmm, couldn't this application derive two keys from SK -- one for sending encrypted info immediately, and another for future usage as you suggest? I think what @kevinlewi is zeroing in on is the desire to remove application-specific knobs from the handshake, since it complicates the specification and implementation.

**Comment by hugokraw** [comment]
> Hmm, couldn't this application derive two keys from SK

Yes, it could. In my eyes it is a less elegant solution and requires the application to understand how to derive these two keys and handle the secure information. 

I agree with reducing as much as possible the security decisions an implementation/application needs to make (such as "should I  send this in the clear or encrypted") but whether I need to send something or not as part of the 3rd message (w/o having to decide on encrypting it or not) is a simpler question for the implementation. 

However, since this is an issue that does not have immediate security consequences (except for applications that may handle insecurely information that could have been accommodated in einfo3) I will go with your preference.

**Comment by bytemare** [comment]
Hello,

if I may, my two cents.

As an [implementer](https://github.com/bytemare/opaque), I find this discussion very interesting and am very happy it takes place. I did not understand the necessity of `info2 `and `info3 `as `einfo2` and `einfo3` were available (there would be a redundancy having the plaintext message and encrypted message), and agree that leaving them out would be preferable.

As for encrypting data in the third message, it really is a specific need of some applications and their choice to send it at that moment, hence not the protocol's responsibility. The document could give indications to implementors and users on how to properly use the output shared secret key, and cite immediate usage for encryption as an example.

**Comment by kevinlewi** [comment]
> The document could give indications to implementors and users on how to properly use the output shared secret key (e.g. derive per need - encryption, token, etc.), and cite immediate usage for encryption as an example.

Thanks, I think this is a good suggestion -- perhaps it would be worth adding a short sentence/paragraph to explain this.

**Comment by stef** [comment]
i have not quite understood concrete applications of these fields. however i have a feeling that the `*info*` fields can be related to protocols building upon opaque and can be used to convey protocol specific info, while the application would always use shared secret SK.

**Comment by kevinlewi** [comment]
@stef The purpose of these fields is to allow for the sending of information that can be authenticated (in the case of info1) and authenticated+encrypted (in the case of info2) **before** the shared secret SK is established.

I believe this issue may also be closed now that the info fields have been clarified, but please reopen if there is more discussion to be had here.

**Comment by stef** [comment]
thanks @kevinlewi i do understand what security properties these fields come with. what i wonder is concrete examples/use-cases how/where these fields are used - specifically what they would contain. one might assume that e.g. the MHF parameters would be such, but iirc that is not a good example. what would be good examples?
