### ISSUE TITLE
Encryption in the AKE section

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#111]
What encryption method should we use to encrypt the `einfo2` field of the AKE section?

I propose that we go with a simple XOR + HKDF based approach. Namely, take the current `Ke2` encryption key, feed it as input to `HKDF-expand`, and xor it with the plaintext to be encrypted. We can obtain the length parameter for HKDF-expand by simply measuring the length of the plaintext (correspondingly, the length of the ciphertext when we need to decrypt).

This XOR-based encryption method does not provide integrity, and only works for a single use of the `Ke2` encryption key, but I believe this is OK because `Ke2` only gets used exactly once anyway, and integrity is already provided by the MAC that is computed using `Km2`.

In particular, I want to avoid using more heavyweight but traditional algorithms like AES-GCM-256 / ChaCha20-Poly1305 because this increases complexity of the specification.

Thoughts? @hugokraw @chris-wood

**Comment by hugokraw** [comment]
Several comments:
- While using GCM seems heavyweight relative to simple xor, some implementations may prefer it to xor since they already have the code that uses GCM for handshake traffic protection, e.g., borrowed from TLS. But fixing the encryption method avoids negotiation which is a real simplification. If  @chris-wood is ok with this, then I am ok with it too.
- One needs AEAD here. The fact that it is a one-time key does not replace that requirement. For example, if an application were to send some negotiation information under einfo2, an attacker could flip some bits to change the offered security parameters.
- The question that remains is whether to add an HMAC on top of the xor-generated ciphertext for achieving authenticated encryption or to count instead on the 3DH MAC for that purpose. Doing the latter would be secure and would indeed eliminate the need for the additional HMAC (and the derivation of an additional HMAC key). I do dislike this idea on "principle" grounds. I always advocate the principle that one should not use the same component for two different purposes, see for example https://mailarchive.ietf.org/arch/msg/cfrg/5ithq2sRpf7QZZ_pk_jrdGJwy3k/
In the case at hand, I can think of a future variant of the protocol where the server sends the MAC on a 4th flow, thus removing the MAC protection of  einfo2 (this case is not completely hypothetical: Stas and I have a variant of OPAQUE with some interesting properties that just does that). However, if you guys think this consideration is too academic and a note on it would suffice then I can go with it. 
- One has to be careful about determining the length of the plaintext to be encrypted; ambiguity in determining length leads to some attacks in some cases.

**Comment by kevinlewi** [comment]
Thanks for the comments @hugokraw!

> The question that remains is whether to add an HMAC on top of the xor-generated ciphertext for achieving authenticated encryption or to count instead on the 3DH MAC for that purpose.

I agree with these points. However, I am leaning towards relying on the 3DH MAC and omitting the "extra HMAC on top of the xor-generated ciphertext", although I think we can (and should) definitely add a note in the description of the encryption of einfo2 that we critically rely on the 3DH MAC for integrity (and that future amendments should take this into account when modifying the protocol).

The main reason why I would like to avoid adding another HMAC is that it seems wasteful in terms of bandwidth. This will increase the message length by another 16 or 32 bytes, even if einfo2 is only 1 byte long -- and in the case where einfo2 is 0 bytes long, do we still generate the HMAC? If so, it seems wasteful, and if not, then implementations must take care to check for the length of einfo2 and case on whether or not it is empty. While doable, it means that when we generate test vectors for implementations to match against, we may need to generate an extra set of test vectors that ensure that implementations explicitly do this check.

**Comment by hugokraw** [comment]
If einfo2 is omitted then no need for the HMAC. I am not sure how crucial the bandwidth issue is and if it is enough of a reason to  make this decision (I would prefer to have the HMAC in the spec and havea note saying that if bandwidth is critical enough then the HMAC can be skipped, assuming the 3DH MAC stays in that same flow. If we do decide to forgo the HMAC all together then there should be a note on the essential need for the 3DH MAC in the same flow AND that no action should be taken on the basis of information encrypted under einfo2 before that 3DH MAC is verified.

**Comment by bytemare** [comment]
Does that mean that 3DH will be used exclusively as the AKE ?

**Comment by hugokraw** [comment]
Applications can choose to use any AKE they want with OPAQUE. For example TLS would use their handshake AKE (essentially SIGMA-I). IKE  and Signal could use it with variants of SIGMA-R and 3DH, respectively, and PQ AKEs could use it with some PQ KEM-based protocols. The 3DH protocol as specified here serves as one fully-specified AKE for applications that do not want to develop or adapt other AKEs and, very importantly, as a basis for interoperability testing. Probably also as a "must implement" for implementations that call themselves "compliant" with the standard (but this may not apply here as this is an informational RFC, I guess). @chris-wood can say more in this regard.

**Comment by kevinlewi** [comment]
> but this may not apply here as this is an informational RFC, I guess

My understanding is that we are very much shooting for a concrete RFC for implementations to measure compliance against.

> Does that mean that 3DH will be used exclusively as the AKE ?

That is the current direction that we are going in. @chris-wood posed this question to the mailing list (https://mailarchive.ietf.org/arch/msg/cfrg/N5AsUuSTEBcrfGCgxirPI0xFkps/), as we are also trying to figure out if we should be supporting AKEs other than 3DH here.

**Comment by kevinlewi** [comment]
Given that we now implement the XOR + HKDF based approach here (https://github.com/cfrg/draft-irtf-cfrg-opaque/blame/master/draft-irtf-cfrg-opaque.md#L1023-L1024), I believe this issue can be closed.

Please reopen if this is still unresolved!
