### ISSUE TITLE
Inconsistency between OPRF ciphersuites in draft-irtf-cfrg-voprf and draft-irtf-cfrg-opaque

### ISSUE THREAD

**Issue by rot256** [cfrg/draft-irtf-cfrg-opaque#146]
draft-irtf-cfrg-voprf lists the following OPRF  instanciations:

  OPRF(ristretto255, **SHA-256**)
  OPRF(decaf448, SHA-512) 
  OPRF(P-256, SHA-256)
  OPRF(P-384, SHA-512)
  OPRF(P-521, SHA-512)

However section 5 of draft-irtf-cfrg-opaque, says:

   An OPAQUE configuration is a tuple (OPRF, Hash, MHF, EnvelopeMode).
   The OPAQUE OPRF protocol is drawn from the "base mode" variant of
   [I-D.irtf-cfrg-voprf].  The following OPRF ciphersuites are
   supported:

   *  OPRF(ristretto255, **SHA-512**)
   *  OPRF(decaf448, SHA-512)
   *  OPRF(P-256, SHA-256)
   *  OPRF(P-384, SHA-512)
   *  OPRF(P-521, SHA-512)

It seems like it should be SHA-256 in both places (targeting 128-bits of security)?

**Comment by chris-wood** [comment]
The [editor's copy](https://cfrg.github.io/draft-irtf-cfrg-voprf/draft-irtf-cfrg-voprf.html#name-oprfristretto255-sha-512) of draft-irtf-cfrg-voprf uses OPRF(ristretto255, SHA-512), which is why OPAQUE uses it. We chose SHA-512 because implementations using ristretto255 are more likely to also have a SHA-512 implementation (due to Ed25519 requiring SHA-512). See [this PR](https://github.com/cfrg/draft-irtf-cfrg-voprf/pull/203) and related issue(s).
