### ISSUE TITLE
3DH and X3DH

### ISSUE THREAD

**Issue by claucece** [cfrg/draft-irtf-cfrg-opaque#163]
Apologies if this has already been discussed or if it does not take into account security considerations already discussed.

The document describes that it is using 3DH as defined by Signal. However, this might not be completely accurate as Signal uses X3DH (as described here: https://signal.org/docs/specifications/x3dh/); even though, at the beginning, they were indeed using 3DH, as described here: https://signal.org/blog/simplifying-otr-deniability/ . So maybe there is a place to change that reference in the document.

The reason why Signal moved from 3DH to X3DH are many, but one of them is due to an attack on forward secrecy as provided by 3DH: an active adversary modifies the first flow from the Initiator to use an adversarially controlled ephemeral key, captures and drops the response from the Receiver, and then compromises the Initiator’s long-term secret key. This attack requires a powerful adversary. This is also addressed in the specification itself (https://signal.org/docs/specifications/x3dh/ , section 4.5) and by the paper: https://content.sciendo.com/downloadpdf/journals/popets/2018/1/article-p21.xml

Signal’s X3DH protocol somewhat mitigates this attack by using signed prekeys. 

I haven't have the time to analyse this attack in the specific context of OPAQUE; but it could be that this has already been taken into account.

cc./ @chris-wood

**Comment by jhoyla** [comment]
I'm not sure that X3DH actually stops the attack.
This attack is actually mostly an attack on the definitions.
PFS says that as long as the LTKs are not compromised before the protocol completes then the attacker cannot derive the session key.
This leads to two points:
1. If you consider that the server's identity and signed prekey are both LTKs (in as much as they are reused across sessions) then the attack on 3DH works just as well.
A powerful attacker modifies the first flow to change the ephemeral key to one it controls, and then later compromises the server's identity and signed prekey.

2. The attack on both 3DH and X3DH disappears if you add an explicit key confirmation step. In this case, client would not complete the protocol until it had received explicit proof that the server knows the derived key. 
This requires the attacker to compromise the LTKs _before_ the protocol completes, thus meeting the definition of PFS.

In the case of OPAQUE the message KE2 includes a MAC keyed with Km2, which is derived from the output of 3DH, giving the client key confirmation.
The server gets key confirmation from the client from KE3, because of the MAC keyed with Km3. 

So w.r.t. the draft, I think we should clean up the text:
1. to say that Signal uses X3DH, it's important to get these things right. 
1. to say that the AKE does _not_ need explicit key confirmation, because OPAQUE has a separate key confirmation step.
2. to make it easier to see where the keys actually come from, because at the moment it's a bit hard to see that Km2 is dependent on 3DH.

**Comment by bytemare** [comment]
My comment is not adding anything useful to the conversation, but just FTR that the link in the doc points to [this](https://signal.org/docs/specifications/doubleratchet/#recommended-cryptographic-algorithms), and I think it should point to [this](https://signal.org/docs/specifications/x3dh).

**Comment by claucece** [comment]
Thanks @jhoyla I agree. 
I'll send a PR and cc you ;)

@bytemare 

> My comment is not adding anything useful to the conversation, but just FTR that the link in the doc points to this, and I think it should point to this.

3DH is defined here: https://signal.org/blog/simplifying-otr-deniability/ (section: Potential Simplifications and Improvements) I think that is the document to point to. I don't think we should include the link to X3DH, as it might confuse readers but rather mention that Signal uses this variant. 

Thank you!

**Comment by bytemare** [comment]
Oh yes, totally agree! I didn't see it was there 👍

**Comment by bytemare** [comment]
Oh yes, totally agree! I didn't see it was there 👍

**Comment by kevinlewi** [comment]
ccing @hugokraw in case he has any thoughts on whether or not it would be necessary to move to X3DH instead of 3DH.

**Comment by hugokraw** [comment]
No need to move to X3DH. If by that one means using pre-signed DH values then such move would contradict the basic definition (and functionality) of a PAKE that does not assume any long-term keys on the client side other than the user's password. As for the attack @claucece points to, this is addressed (as @jhoyla explains) by having explicit authentication by both parties via the MAC values. Strong forward secrecy is a built-in requirement in OPAQUE.

As for the relation to Signal, my original text said that "3DH serves as a basis for the key-exchange protocol of SIGNAL." which I think is accurate. The reason we are using 3DH is because it is simple to describe and it is relatively efficient (more specifically, it is there because HMQV, which two less exponentiations, has a patent)

**Comment by claucece** [comment]
Thank you @hugokraw for the explanation and @kevinlewi for the pointer ;) 

We talked this offline with @jhoyla extensively and agree on this. 

We will send a PR just with clarifications for a reader that gets confused, and cc you all into it for your comments ;)

**Comment by chris-wood** [comment]
@claucece, @jhoyla: should we still expect a PR for this issue? If not, can we close this out?

**Comment by claucece** [comment]
Yes! sorry about that. Thank you for reminding me. I'll send today, as I'm re-reading the draft ;)

**Comment by chris-wood** [comment]
Fixed in #216.
