### ISSUE TITLE
3DH: highlight the usage of client_info and server_info

### ISSUE THREAD

**Issue by armfazh** [cfrg/draft-irtf-cfrg-opaque#169]
In the 3DH instantiation, the fields `client_info` and `server_info` are marked as optional and application-specific. 

```
client_info
Optional application-specific information to exchange during the protocol.

enc_server_info
Optional application-specific information to exchange during the protocol encrypted under key Ke2, defined below.
```

The request here is to highlight in the document what are the possible use cases of these fields, and to remark the relevance of having these fields vs not having them at all.

**Comment by bytemare** [comment]
Some observations about these fields

I'm not aware of many significant use cases for these fields. I'm very interested in examples that would undoubtedly justify these fields are kept. I can come up with valid ones, but they are weird enough they don't seem to solve any existing problem.

An important point to consider The `server_info `has strong constraints.
_If it is used for client-specific values_, it may leak info about the client's existence and activity, harming the client enumeration mitigation effort to some degree. That means that it must be of constant length, whether the user exists or not. Keeping this coherent across and for all clients in time doesn't look to scale reasonably well.
This being considered, application-specific `server_info `might not even need encryption if we consider an attacker already has access to the application.

Then again, `server_info `in KE2 instead of being in a message post-OPAQUE must justify a reasonable practical, security, or performance point. This point might be very niche and application-specific as well, thus not justifying `server_info `to be kept in-band. Maybe extracting its concept and specifying it in the appendix would be an acceptable compromise.

Also, there's a very interesting thread in #74

**Comment by afbase** [comment]
# Prior Art And Use Cases

If any language from the OPAQUE draft is referenced below, it is in reference to the language found in commit [e221eaf](https://github.com/cfrg/draft-irtf-cfrg-opaque/tree/e221eaf702c2f018ad73bdfd3e043abbf8706b1f).

>The request here is to highlight in the document what are the possible use cases of these fields, and to remark the relevance of having these fields vs not having them at all.

_Please_ critique my use cases with the critique, let's focus on whether the client_info and server_info is useful here.

I will follow up with prior art examples of where extra server information is provided in other authentication schemes in another comment (either Tuesday or Wednesday evening Pacific time)

## Use Case 1 - Load Balancer with Multiple Backend Servers

Suppose we have:
  1. a client, 
  1. loadbalancer (LB),
  1. N backend servers (ASCII Diagram -> N=3),
  1. The client has completed a registration flow

```
                        ┌──────┐
                        │Client│
                        └──┬───┘
                           │
                           │
                           │
                           │
                           │
                           │
                           ▼
                  ┌───────────────┐
        ┌─────────┤ Load Balancer ├──────────────────────────────┐
        │         └────────┬──────┘                              │
        │                  │                                     │
        │                  │                                     │
        │                  │                                     │
        │                  │                                     │
        │                  │                                     │
        │                  │                                     │
┌───────▼───┐              │   ┌───────────┐                 ┌───▼───────┐
│ Backend 1 │              └──►│ Backend 2 │                 │ Backend 3 │
└───────────┘                  └───────────┘                 └───────────┘
```
Please forgive the one-way direction of flow in the diagram above.  It should be two way and I could not figure out how to do that in asciiflow.

### Use Case 1; Subproblem 1 - AKE via TCP LB Session Persistence

High-Level: The client will communicate with only one backend for the lifetime of the session.  The LB facilitates the routing between client and the backend.  AKE is done between one backend and client.

Is the server_info/client_info useful here?

An example of how might `server_identity` and `server_info` might be used is:
  1. `server_identity`: agnostic value (i.e. it is the same value) across all backend servers
  1. `server_info`: information that would be specific to the backend communicating with the client.

Another sub-subproblem of this is to assume (1) all backend servers accept the client's prior registration flow and (2) that neither backend server hosts the same application.

Is the server_info/client_info useful here?

### Use Case 1; Subproblem 2 - AKE with HTTP LB 

High-Level: The client will communicates with HTTP LB.  AKE is done between HTTP LB and Client.  The HTTP LB also routes information to one of the backend servers.


Is the server_info/client_info useful here?


## To wrap up this post

At this moment, I could potentially see how `server_info` might be useful; I haven't exactly thought about `client_info` in great depth.  I am also aware and totally understanding that this information during AKE might open doors to problems and usage that would be detrimental.

**Comment by chris-wood** [comment]
@afbase could routing information (like the specific backend being used) not be conveyed _outside_ of the OPAQUE messages? Does it need to be authenticated by the handshake?

**Comment by afbase** [comment]
> @afbase could routing information (like the specific backend being used) not be conveyed _outside_ of the OPAQUE messages? Does it need to be authenticated by the handshake?



@chris-wood 
with respect to the use cases above and after some thought about this, the simple answer is no; it is not necessary to be authenticated in the handshake and application (and routing) information can be done after the handshake.  

>I will follow up with prior art examples of where extra server information is provided in other authentication schemes in another comment (either Tuesday or Wednesday evening Pacific time)

Well I've been asking a lot of myself here.  I have given some thought about other prior art in key exchanges and authentication schemes this evening but i haven't quite written much just yet.  Hope to have something tomorrow (wedenesday evening pacific time)

**Comment by afbase** [comment]
>and to remark the relevance of having these fields vs not having them at all.
I am leaning heavily to opine to not having them at all.  I would really like to do a survey of prior KE's and authentication schemes to justify such an opinion but I just don't have the time to really dive deep into various prior art, identify and provide comment on analogous constructions.  

Are there any existing survey papers that might touch this particular issue on (A)KEs?

**Comment by chris-wood** [comment]
I'd like to take a step back and ask whether we can simply remove these two fields altogether, as @armfazh's initial comment seems to suggest. There's a couple reasons for this:

1. Server info must be user-agnostic, i.e., of the same size and generated in the same amount of time for all users, otherwise it  can be a potential side channel breaking user enumeration mitigations. (This is very similar to the challenge we face in [TLS ECH](https://tlswg.org/draft-ietf-tls-esni/draft-ietf-tls-esni.html), and so far we've been punting on that in the technical specification.) Any information that is not user-specific seems like it can therefore either be transported outside of the OPAQUE handshake but in the server's first flight, or after the handshake is complete. 
2. We have no existing use cases for these fields. (I don't view sending the username in client info as a valid use case, for what it's worth.) Moreover, no existing deployed PAKEs have these fields, and no planned use cases for OPAQUE require, to my knowledge, use of these fields, which leads me to conclude that they're really not needed in practice.
3. [RFC8125](https://tools.ietf.org/html/rfc8125) does not require the PAKE to support this type of "early" data, nor does it touch on extensibility. 

This issue seems sharply focused on how extensible we view the protocol. If we want it totally extensible, then keeping these fields make sense, even if we don't have an existing use case. If we want to keep this protocol rigid yet admit future extensibility, we can remove them and say that future specifications can reintroduce them as needed.

As an aside, I'll note that the current way in which the server info is encrypted is really... bespoke. If we are to keep these fields, I think we should strongly consider transitioning to something a bit more like TLS/QUIC, which has separate record and message layers, and encryption happens at the record layer. 

cc @hugokraw

**Comment by hugokraw** [comment]
I understand the desire to simplify the specification as much as possible and reduce options but I also think that we are producing a spec that is supposed to serve a large (and unknown) variety of applications and not accommodating the transmission of server-to-client information in the protocol seems overly restrictive. I do appreciate the simplification this brings to the user enumeration defense (which as noted earlier, would require the length of this message to be user-independent). Overall, there seems to be strong support for removing the encrypted server_info message and since this is a functional decision and not a cryptographic one I will defer to the engineering judgment (*).  I wonder if there should be some  extensibility mechanism for the protocol messages even if it does not include the mechanics of how to encrypt such extensions.  

(*) For general clients, such as browsers, that may not be fully configured for a particular application, the server may need to provide OPAQUE-specific information, e.g. hardening parameters, One could fit this information in the envelope but we are not doing that so we must be assuming that this type of information is transmitted "out of band" (i.e., through some application wrapper) and unauthenticated (except if the whole thing goes inside a TLS tunnel or the like).

Finally, regarding client_info, @chris-wood says that "I don't view sending the username in client info as a valid use case". I guess that this assumes that user information is always transported outside OPAQUE. I am not sure this is a good universal assumption, and since this message does not have the complexities of server_info (it does not require  encryption and does not interfere with user enumeration), I would be inclined to keep it. But I will not go into hunger strike if you think otherwise.

**Comment by chris-wood** [comment]
Sorry for the delay in following up on this! Please see below.

> Overall, there seems to be strong support for removing the encrypted server_info message and since this is a functional decision and not a cryptographic one I will defer to the engineering judgment (*). I wonder if there should be some extensibility mechanism for the protocol messages even if it does not include the mechanics of how to encrypt such extensions.

Indeed. I think we can safely remove this piece of information. What remains, then, is the client info. (The hardening parameters are part of the configuration information, so they would be exchanged alongside the config.)

I did a (albeit quick) survey of PAKE uses top of mind, as well as other asymmetric and symmetric PAKE protocols, with respect to their support for "early" client data. The results are below. (Please attribute errors or inaccuracies to me!)

PAKE use cases:
- [Magic Wormhole](https://github.com/magic-wormhole/magic-wormhole): no application data
- [CHIP](https://github.com/project-chip/connectedhomeip): no application data
- [WPA-2 authentication](https://papers.mathyvanhoef.com/ccs2017.pdf): no application data

Symmetric:
- [J-PAKE](https://datatracker.ietf.org/doc/html/rfc8236#section-2.2): no application data
- [SPAKE2](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-spake2-18): no application data
- [SPEKE](https://eprint.iacr.org/2014/585.pdf): no application data, but identities are transferred
- [CPace](https://datatracker.ietf.org/doc/html/draft-irtf-cfrg-cpace-01#section-3.2): no application data

Asymmetric:
- [SPAKE2+](https://datatracker.ietf.org/doc/html/draft-bar-cfrg-spake2plus-02): no application data
- OPAQUE: application data!
- [AuCPace](https://eprint.iacr.org/2018/286.pdf): no application data, but identities are transferred
- [SRP](http://srp.stanford.edu/): unclear
- BSPAKE: unclear

In general, it seems this is not a useful or sought-after feature, else we would see it more widely used or supported in existing protocols. Given this, possible privacy concerns about sending application-specific information in client info, I'm inclined to drop both application data fields from the handshake. If circumstances change and this prohibits some future application from using OPAQUE, we can always rev the protocol version.

**Comment by FredericJacobs** [comment]
From the use cases I'm familiar with, early data has never really been something that we felt we really needed. 

That said, SPAKE2+ does provide a mechanism to pass authenticated data into the confirmation messages, which is very useful for preventing downgrade attacks on protocol versions and ensure that both parties have agreed on a list of supported versions or anything else that would benefit from being authenticated.

**Comment by chris-wood** [comment]
Closed via #211. @armfazh, please reopen if you disagree!

**Comment by hugokraw** [comment]
I am replying here since this issue is closed and I don't know how to reply
directly from github in this case (it is ok if you laugh at me, just not
loud enough that I could hear it :-).

I am glad you agree to adding this way of authenticating information
passed/agreed between client and server. What's not clear to me is what is
meant by "prepended to the transcript"? When/how is it prepended and how is
authentication applied to it? Is it via the MAC on the wire or via KDF? Or
some other form?

Unrelated question: Chris references other a/PAKE protocols. Do any of them
have a detailed *full* specification like the one we are developing here?
Or a working implementation?  (Anything less detailed than that will not
care about specifying if implementation data needs or does not need to be
communicated as part of the protocol.)

**Comment by chris-wood** [comment]
> I am replying here since this issue is closed and I don't know how to reply directly from github in this case (it is ok if you laugh at me, just not loud enough that I could hear it :-).

No problem =)

> I am glad you agree to adding this way of authenticating information passed/agreed between client and server. What's not clear to me is what is meant by "prepended to the transcript"? When/how is it prepended and how is authentication applied to it? Is it via the MAC on the wire or via KDF? Or some other form?

By "prepend to the transcript," we mean that the transcript used to derive keys includes: (1) the shared context string, and (2) then all handshake messages sent on the wire. (For comparison, client_info was also authenticated by including it in the transcript. The difference here is that client_info was sent on the wire in the handshake message, whereas the shared context string _need not_ be sent on the wire.) 

> Unrelated question: Chris references other a/PAKE protocols. Do any of them have a detailed *full* specification like the one we are developing here? Or a working implementation?

I'm not sure what you mean by "full" specification here. CPace and SPAKE2+, for example, are "full". OPAQUE just happens to cover more wire format details, leaving less to implementers to figure out.

**Comment by hugokraw** [comment]
Thanks for the explanation. I assumed it was via the KDF indeed. I have a
general preference for authenticating things via the authentication
mechanism in the AKE rather than via the KDF (it meshes better with the
logic of the protocol). Note that you could add this out-of-band value to
the information being MACed instead of under the KDF. But it is ok to do it
via the KDF too.

While at it, what was your motivation to include the full transcript  into
the KDF? Did you have a specific reason for it or was it based on "best
practice" and/or consistency with TLS 1.3 approach?

**Comment by chris-wood** [comment]
> While at it, what was your motivation to include the full transcript  into the KDF? Did you have a specific reason for it or was it based on "best practice" and/or consistency with TLS 1.3 approach?

It seems to be best practice and overall easier to implement. Clients and servers can just fold their entire handshake messages into the running hash, rather than pick out specific fields to include. That is, the logic for the server is basically: 

1. Update hash with context
2. Read message from wire
3. Update hash with message
4. ... do rest of the protocol

**Comment by hugokraw** [comment]
Thanks.

**Comment by afbase** [comment]
>I did a (albeit quick) survey of PAKE uses top of mind, as well as other asymmetric and symmetric PAKE protocols, with respect to their support for "early" client data. The results are below. (Please attribute errors or inaccuracies to me!)

@chris-wood thank you for taking the time to write this up!
