### ISSUE TITLE
Serialization of envelope: swap ordering of inner_env and auth_tag?

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#177]
Currently, the serialization of the envelope is defined as follows:
```
struct {
 EnvelopeMode mode;
 opaque nonce[Nn];
 opaque auth_tag[Nm];
 InnerEnvelope inner_env;
} Envelope;
```

Any reason why auth_tag is not at the end of this struct? Would it suffice to put it at the end, after the inner_env parameter?

cc: @bytemare , @chris-wood

**Comment by bytemare** [comment]
Maybe I should have specified this somewhere, as you're not the first asking this :) ( someone else asked this somewhere in the comments of the PR)

The reason the authentication tag is at this place is that it will always be exactly there, regardless of the envelope mode (and thus the inner_envelope length), since `mode`, `nonce`, and `auth_tag` will always have the same length. I believe this makes deserialization a bit easier and might avoid deserialization errors in implementations.

What do you think?

**Comment by bytemare** [comment]
After discussions offline, and with regard to #180 , the application should provide and specify the envelope mode, and thus know about the inner envelope's length. The auth tag is therefore not required anymore to be in a fixed position and can safely be put back at the end of the envelope.
