### ISSUE TITLE
Promote discussion of client enumeration attacks

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#253]
We don't discuss this until we get to CreateCredentialResponse, so it comes out of nowhere. Let's see if we can bubble this up to the intro or protocol overview.

**Comment by hugokraw** [comment]
I might have remarked on this already but the definition for the masking key as  "A key used by the server to preserve confidentiality of the envelope during login." may create confusion as it seems to imply that this is necessary for the security of the protocol. It is, as the name says, a masking technique applicable only to counter enumeration attacks and independent of the security of the protocol. This needs to be clarified and the definition should reflect this. (Otherwise, I will confront years of confusion and explanations in IETF lists and others :-)

Related to user enumeration and how critical it is for applications: There is an obvious opportunity for enumeration via "forgot password" in current practice and I see that it is common not to defend against it - this is an this example from Macy's:   "The email address you entered doesn't match any account. Check the spelling or try a different email."  Are people taking enumeration seriously enough? Note that defending in this case require the protection against timing attacks, etc. that are not easy in this case either. See https://cheatsheetseries.owasp.org/cheatsheets/Forgot_Password_Cheat_Sheet.html.  
You may want to comment when talking about measure to avoid timing attacks that this is similar to what happens in today's systems at least when dealing with password resets. 

In Section 6.1.2.2 where it says:
   It is RECOMMENDED that a fake client record is created once (e.g. as
   the first user record of the application) ...
I wasn't sure at first if this recommendation is per fake user or one record used with all fake users. Of course you mean the latter but I would make the text more clear about this.

Also, it would be good if there was a way to highlight the condition "if client enumeration prevention is desired," in the text (boldface?).

In 10.8, it says "OPAQUE prevents these [enumeration] attacks during the authentication flow."  OPAQUE does not prevent them. It is up to the server to do so by following the explanations in 10.8. The only thing OPAQUE does is to mask the envelope as an anti-enumeration measure. The rest are optional server implementation measures. 

Are there any other specifications that are only needed to protect against enumeration attacks?

**Comment by bytemare** [comment]
Regarding "Forgot password" measures, it's bad practice to throw an error back to the client saying the account doesn't exist. An easy way to avoid this problem is, in every case, returning "An email to reset the password was sent to abc@mail if an account for it exists", and then only send a mail if the e-mail address has been registered.

Note that websites that heavily rely on the security of the users's email provider might as well completely bypass passwords and use magic links instead. I think Medium does it.

**Comment by hugokraw** [comment]
I agree that what you suggest is the right way to address this issue. I was wondering if the fact that they don't do it means that they don't care too much about the attack. Also, as the link I included explains, you have to be careful about timing attacks in that solution too.

**Comment by bytemare** [comment]
The impact of user enumeration varies greatly from one service to another. I suppose every online service estimates their threat model as they seem fit, and always according to their knowledge and capabilities. I wouldn't know whether this particular one does.

I think few online service do everything perfectly according to best practices. As usual it boils down to perceived need, security culture, and willingness to invest.

As of the timing attack, it may be interesting to mention this, indeed. And it makes me wonder: how much security considerations should we add to the document ? Could we outsource it and add a link to your document instead ?

Where the barrier between what security should be addressed in the spec and what is application security outside of OPAQUE is an interesting one.

**Comment by hugokraw** [comment]
The current draft mentions timing attacks in  section 10.8. I believe that the spec needs to address enumeration attacks and describe the defenses against it. My only question is whether it has to build-in these defenses as part of the default protocol or as an  optional extension also defined in the current document. The current spec takes the former approach defining the masking_key and the mechanism to xor the envelope with a one-time pad derived from masking_key. My preferred approach would be to define the derivation of masking_key as part of the mandatory spec but leave its use as optional (as we do with the export_key). Then, specify, as an *optional* mechanism, how to use masking_key  to address enumeration attacks (namely, the    derivation of credential_response_pad and  the generation of masked_response). The reason for this separation into mandatory and optional is to avoid the extra *conceptual* complexity of credential_response_pad derivation and response masking for those that do not need it. Also, to make it clear that masking of the envelope does not have a security function other than protecting against enumeration attacks.
But I do not see these issues as essential and whatever you guys decide is fine with me. But in either case, we need to say clearly that masking_key and its use is only needed against enumeration attacks, and not to refer to this masking as "encryption" or "confidentiality" as we do now in some of the text.

**Comment by bytemare** [comment]
I think this is a great idea and totally agree we should take this approach!

**Comment by chris-wood** [comment]
I don't think think the use of masking_key should be optional. The protocol is already complicated enough as-is, and forcing another (non-essential) decision onto implementers seems like it'll yield undesirable outcomes. Making it mandatory, as is the case now, removes that decision point and allows for safer server-side implementations.
