### ISSUE TITLE
Replace symmetric masking_key protection with an asymmetric method

### ISSUE THREAD

**Issue by bytemare** [cfrg/draft-irtf-cfrg-opaque#310]
Currently, one of the client enumeration mitigation techniques is to encrypt the server's login response with a symmetric key furnished by the client during registration.

The notion that there is data in that record that is supposedly secret (the `masking_key`)  puts some constraint on the server and the operator of the user database. The "_OPAQUE manual_" would read _"this key is a secret symmetric encryption key used to protect against client enumeration_", and any good practice would hence indicate that this needs more attention than if there wasn't secret data.

I'm trying to see this from the point of view in some years when OPAQUE is mainstream and deployed everywhere one can think of, and millions of developers are using it in their apps. The less poisonous/radioactive the record is (or just appears to be) the better.

I have more trust in protocol implementers doing the right machinery to build OPAQUE than I have in people using it correctly. So the smaller the operational risk surface, the better.

___

My suggestion is to replace the current masking mechanism with a non-interactive DHKE to encrypt the envelope in transit. Replace the symmetric `masking_key` with an asymmetric user public key.

On registration, the client uses a server-provided public key (in the registration response) to encrypt its record to that key and send the result to the server. This adds confidentiality to the record as discussed in #240.
On login, the server encrypts the envelope to the client's public key and sends that along in the credential response. The client recovers its private key (just like now) and can decrypt that ciphertext.

**This brings the advantage of having a less sensitive client record since it won't contain any secret value anymore.**

HPKE could be a good candidate for this.

cc @chris-wood @kevinlewi

**Comment by bytemare** [comment]
**Proposed changes**

**Change 1**
On registration, the server sends a public key that the client will use in Change 3
~~~
struct {
  uint8 data[Noe];
  uint8 server_public_key[Npk];
  uint8 server_hpke_key[Npk];
} RegistrationResponse;
~~~

**Change 2**
Instead of the `masking_key` in the record, the client derives a `client_hpke_key` from the OPRF output and places it in its registration record.
~~~
struct {
  uint8 client_public_key[Npk];
  uint8 client_hpke_key[Npk];
  Envelope envelope;
} RegistrationRecord;
~~~

**Change 3**
The client uses the server's `server_hpke_key` to encrypt that `RegistrationRecord` to ensure its confidentiality (cf #240). The message sent instead to the server at registration would then be the following
~~~
struct {
  uint8 masked_record[???];
} RegistrationFinalize;
~~~

**Change 4**
In CredentialResponse during login, the new `masked_response` field is the encryption of `server_public_key||envelope` using the `client_hpke_key` from the record.
~~~
struct {
  uint8 data[Noe];
  uint8 masked_response[???];
} CredentialResponse;
~~~

**Change 5**
The client recovers the pseudorandom key and `client_hpke_key` (like in Change 1) and decrypts the masked_response to finalize the key recovery.

**Comment by hugokraw** [comment]
I have the feeling that I am misunderstanding the intention here. So pardon me if what I am writing makes no sense (please explain to me again).

Is client_hpke_key a symmetric key with the same functionality as masking_key but with a different name? Is the only substantial change here the sending of a PK from the server during registration for  implementing a secret channel from client to server during registration? If this is all then I would prefer not to add this mechanism. In the large majority of cases, in particular those doing registration over server-encrypted TLS, this would not be needed. In other cases, , the application will need to create such a secret channel by sending a (possibly ephemeral) public key over the authenticated channel. Is it worth adding complexity to the OPAQUE spec for something that may only be needed in a minority of cases? (In general, it frustrates me how much complexity this "stupid" enumeration issue introduces.)

Btw, one way to eliminate the secrecy of masking_key and the need for a secret channel during registration, is to use a client's public key instead of a masking key to mask the server's message during login. The client will produce a second (private,public) key pair  (additional to the one used by regular OPAQUE)  from the OPRF output and send it to the server during registration. During login, the server encrypts an ephemeral masking key under this client's public key and uses the masking key to mask the server's login response. This prevents the need for a secret channel during registration and the need to store the secret masking_key at the server. However, it adds complexity to the protocol and, even worse, people will end reusing the OPAQUE client public key for this masking purpose. Also, one would need to require that the PK scheme in use be "key private" in the sense  of Bellare et al https://iacr.org/archive/asiacrypt2001/22480568.pdf.

**Comment by bytemare** [comment]
Hello Hugo,

client_hpke_key is an asymmetric key, for the exact purpose you describe in the second part of your message :)

**Comment by bytemare** [comment]
Regarding key privacy, the scheme I'm suggesting for the registration is directly intended for that: the client encrypts the client record under the server's hpke key, thus hiding the client's public key.

I agree that this brings some complexity. That's why I'd like to discuss the benefits vs the added complexity. It would also be interesting if we find solutions to reduce the added complexity.

**Comment by hugokraw** [comment]
Why do you need to encrypt the client's public key? If this is for key privacy as in the Bellare paper, then encrypting the public key may not be enough to ensure key privacy. In any case, while I hate to require a secret channel just for the (symmetric) masking key, I feel this alternative using public key encryptions adds complexity and can lead to shortcuts that reuse of the OPAQUE public key for this masking encryption. Yet, if you guys prefer this solution, I can live with it.

**Comment by bytemare** [comment]
From what I understand, the key privacy property in the paper is to ensure the privacy of the receiver (i.e. client) public-key in the case it is already public. In our setting, the client's public key is not known by an eavesdropper unless they had access to the cleartext client record on the server. If I'm not mistaken, the lack of that property is not a problem here.

I agree that this solution adds some sort of complexity and some more configuration options. But maybe we can figure something out to reduce that overhead.

**Comment by daxpedda** [comment]
As an implementer I think this adds a great deal of complexity, but I believe it would be worth it. If I understand this correctly, that would not only protect the transport, but also any potential database leaks from revealing the masking key, as long as the servers private and public key aren't compromised.

So overall an improvement, the spec could also specify to make it optional, but standardizing it would still benefit implementers a lot.

**Comment by hugokraw** [comment]
In the basic protocol, the server stores two per-user secrets: an OPRF key and a private key for the server. However, the former can be I avoided if the user's OPRF key is derived from a master PRF, and the latter is prevented if the server uses the same private key with all users. In this case, the masking key would be the only secret value to stored in the user's record. I do find value in @bytemare  effort to avoid storing such secret value. However, a simple solution is to use yet another system-wide PRF 
 to derive per-user pseudo-random pads to encrypt the masking key.  The public key approach as suggested by @bytemare and supported by @daxpedda could work, but it is not theoretically sound: If the PK encryption scheme does not have the same space of ciphertexts (this is the case of RSA), then the masking using PK encryption may not be indistinguishable between existing and non-existing users.  This is not an issue with elliptic curves so at the moment this maybe a theoretical concern only. Not sure about PQ schemes.  One more element to consider: If an attacker has access to a user's record, then it does not need to mount an enumeration attack against that user; it already knows the user exists. Since the masking key is only needed to counter such attack, disclosing it to the attacker in this case does not seem a problem. Food for thought. I may well be missing some other considerations to support the PK variant.

**Comment by daxpedda** [comment]
> If an attacker has access to a user's record, then it does not need to mount an enumeration attack against that user; it already knows the user exists.

I didn't think about that. If I understand this correctly, there is really no point to store the masking key in it's encrypted form (whatever form that encryption might take, IANA cryptographer, I will let you guys hash that out), so the masking key should really only be encrypted during transfer of the `RegistrationRecord` from the client during registration?

**Comment by bytemare** [comment]
What we can do is to add some text in the security section suggesting this solution for people considering that risk needs to be addressed. Piggy backing on #306
