### ISSUE TITLE
Should the OPRF seed and client keypair be different per client?

### ISSUE THREAD

**Issue by jamesw1892** [cfrg/draft-irtf-cfrg-opaque#346]
[Paragraph 1 of section 5](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#section-5-1) states that the same keypair can be used with multiple clients and different OPRF seeds can be used for each client.

Whereas [section 5.3](https://www.ietf.org/archive/id/draft-irtf-cfrg-opaque-07.html#name-finalize-registration) states that different keypairs can be used with each client and the same OPRF seed SHOULD be used for all clients.

This seems to be a bit confusing, it might be worth clarifying this in both places in the spec.

**Comment by bytemare** [comment]
Hi James,

Indeed, the server can either use unique AKE key pairs for each client, or for a subset, or the same for all of them. They point is to associate that key pair with the client as to use the right one during execution.

The OPRF key _can_ be the same or different for each client. Since it is mixed with the client id when used, a unique per client OPRF key is derived, whatever the seed is. This document specifies a method where the seed is global.

Reading your comment and then the sections I agree that this might be confusing. Do you have a suggestion to make this clearer ?

**Comment by chris-wood** [comment]
This has been fixed on the editor's copy, which no longer implies that the OPRF seed is different across users. (It's important that this seed is the same for all users for the purposes of preventing enumeration.) Closing as such. Please feel free to reopen if you think more should be done here.
