### ISSUE TITLE
question re derivation of oprf_key from oprf_seed

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#450]
in `CreateCredentialResponse`  the following happens:

```
  seed = Expand(oprf_seed, concat(credential_identifier, "OprfKey"), Nok)
  (oprf_key, _) = DeriveKeyPair(seed, "OPAQUE-DeriveKeyPair")
```
this complex approach is unnecessary in the ristretto255 setting, there is safe implementations that provide a scalar.  is it safe to simply replace the above with 

```
oprf_key = crypto_core_ristretto255_scalar_random()
```

if it is not safe, why is that?

reducing complexity is in the interest of reviewers and implementers.

**Comment by kevinlewi** [comment]
So in order to be compliant with the test vectors, we do need to compute the oprf_key parameter using this DeriveKeyPair procedure. This was introduced in https://github.com/cfrg/draft-irtf-cfrg-opaque/pull/329, see the discussion there (also see: https://github.com/cfrg/draft-irtf-cfrg-opaque/issues/241). It also ensures that the oprf key is deterministically derived from this seed, which is to help prevent against client enumeration attacks. See the section on "Client Enumeration" in the draft.

Also, note the following paragraph in that section which may apply to you:

> Finally, applications that do not require protection against client enumeration attacks can choose to derive independent OPRF keys for different clients. The advantage to using independently-derived OPRF keys is that the server avoids keeping the oprf_seed value across different clients, which if leaked would compromise the security for all clients reliant on oprf_seed, as noted in {{DL24}}.

**Comment by stef** [comment]
ah, client enumeration mitigation is an acceptable reason. thank you!
