### ISSUE TITLE
how to mixin the client and server identity into the oprf?

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#452]
the following section:

> As specified in Section 5 and Section 6, OPAQUE only requires the client password as input to the OPRF for registration and authentication. However, if client_identity can be bound to the client's registration record (in that the identity will not change during the lifetime of the record), then an implementation SHOULD incorporate client_identity alongside the password as input to the OPRF. Furthermore, it is RECOMMENDED to incorporate server_identity alongside the password as input to the OPRF. These additions provide domain separation for clients and servers; see Section 10.2.

is ambiguous should the client and server identity be concatenated with the password as input to blind() or also to finalize()?
is concatenation enough? or is it necessary to prefix the two identities with a length prefix (and also the password?)

**Comment by kevinlewi** [comment]
Yes, there is some ambiguity here but ultimately it is up to the implementor to decide. Concatenation + length-prefixing should suffice, but the exact mechanism for this is outside of the scope of the document. And yes, this should be done for both blind() and finalize(), as the "input to the OPRF" is supplied in both stages.

**Comment by stef** [comment]
ok, but any OPAQUE implementation doing so as recommended will deviate from the test vectors.

> as the "input to the OPRF" is supplied in both stages.

that totally makes sense in hindsight, but is not obvious at all if not very closely read and interpreted.

**Comment by kevinlewi** [comment]
That's true, it is a bit underspecified, but note that this is only an option for applications where client_identity can be persisted on the client. We decided not to include this in the main specification because it is optional (and in some cases too restrictive). So, if an OPAQUE implementation wishes to conform to the test vectors, they would test functionality by replacing the concatenation of client_identity | server_identity | password (or however it's organized) as the actual "password" field as referenced in the test vectors.

Regarding clarity of the text: I suppose I am not exactly sure how to clarify it further. Ultimately what we want to convey is that the "password" field can be replaced with "client_identity + server_identity + password", and "input to the OPRF" is the placeholder which I think captures that. Let me know if you have a (hopefully concise) suggestion for how to improve the clarity here. Thanks!
