### ISSUE TITLE
XOR-based encryption for Ke2 and Ke3 encryption keys in AKE?

### ISSUE THREAD

**Issue by kevinlewi** [cfrg/draft-irtf-cfrg-opaque#83]
From [the definition of Ke2 and Ke3](https://github.com/cfrg/draft-irtf-cfrg-opaque/blame/master/draft-irtf-cfrg-opaque.md#L1071-L1075), the encryption keys used to encrypt the optional Einfo parameters in the AKE section, it seems like the application would need to pick an encryption algorithm for OPAQUE to use here.

Can we avoid this selection and simply use an XOR-based one-time pad for encryption here (is this secure)? Thus, instead of setting key_length to be a fixed constant, it would simply be the length of Einfo2 and Einfo3.

**Comment by kevinlewi** [comment]
@hugokraw ^

**Comment by hugokraw** [comment]
The encryption needs to be authenticated-encryption. One could make the point that because the transcript is mac-ed anyway (currently specified only for 3DH/HMQV), then IND-CPA encryption could be enough, hence also xor.  However, I am always wary of such indirect assurances, i.e., using one element in the protocol (the MAC in this case) for two different reasons. The concern is that in the future, one of the reasons may not be relevant any more (because of some other change in the protocol or its requirements) and people will forget it was needed for another reason. A  good example is SIGMA. We could define that the whole transcript not only is signed but also MACed. Then you could use xor for encryption. But since SIGMA does not really need MACing the transcript then eventually the protocol could be simplified by only MACing the identity forgetting that the MAC also server to implement authenticated encryption. And given that GCM is so widespread now, it would be simpler to specify the encryption as GCM.
Important: Do you want to have a full specification for one of these protocols, say 3DH, at the level of allowing interoperable implementations? In that case we really need to make some choices for instantiating these functions.

**Comment by kevinlewi** [comment]
Thanks for the points. I think the only worry I have with specifying the encryption in this manner is that it brings additional complexity into the protocol, despite not being required for the core OPAQUE functionality. But overall I am supportive of it.

I'm interested to hear what @chris-wood has to say on doing a full spec for one of the AKE protocols.

**Comment by hugokraw** [comment]
I was thinking about this and we do need to have a **simple**, full instantiation of OPAQUE to be used for interoperability testing but also for whoever wants a simple aPAKE with the benefits of OPAQUE. I assume that the modularity of design and specification has some important benefits (e.g., making it easier to integrate with existing AKE protocols such as TLS or IKE) but it may also obscure the simplicity of OPAQUE (e.g, when implemented with 3DH).  We should not let people conclude, erroneously,  that OPAQUE is too complex.

**Comment by kevinlewi** [comment]
Agreed. Is your conclusion that we could still opt for a simple XOR-based encryption scheme here (since the transcript is already mac-ed), and that we could leave a clear note in the specification stating why XOR-based encryption is OK and what would need to change if the transcript were no longer to be mac-ed?

**Comment by hugokraw** [comment]
Yes. That works. I am not sure what would be considered simpler by implementers: encryption implemented by XOR-ing with a bit stream output by HKDF or a call to GCM with a key output by HKDF. Your call, guys.

**Comment by kevinlewi** [comment]
@chris-wood ^

**Comment by chris-wood** [comment]
I think it's probably easiest to stick with normal AEADs for AKE encryption, though note that this really depends on #77 (or more generally AKE specificity). For example, if we go with the "this document just specifies templates for *actual* AKEs," then any future document describing a *specific* AKE with its wire format would deal with this encryption. But if we decide to specify a *specific* AKE in this document, then we'd have to deal with it.

I lean towards being specific in this document, rather than punting to implementers and future document authors. (It seems wrong to deliver a partially baked protocol in the standard.)

**Comment by hugokraw** [comment]
I think we are in agreement to have one full specification that includes the AKE part. Now we "just" need to agree on the details and choices, including which of the three AKEs in the document - HMQV is the most efficient but it is out for IP reasons :-(

**Comment by chris-wood** [comment]
My vote would be 3DH. This would allow us to then sketch HMQV and SIGMA-I variants (sort of as we do now).

**Comment by hugokraw** [comment]
Sounds good to me.

**Comment by chris-wood** [comment]
Closing to track a complete 3DH instantiation in #77.
