### ISSUE TITLE
id missing in CredentialRequest

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#88]
in the section https://github.com/cfrg/draft-irtf-cfrg-opaque/blob/master/draft-irtf-cfrg-opaque.md#authenticated-key-exchange-messages CredentialRequest is defined as:

```
struct {
    opaque data<1..2^16-1>;
} CredentialRequest;
```
and right below that is this line:
> data : An encoded element in the OPRF group. See {{I-D.irtf-cfrg-voprf}} for a description of this encoding.
and in the https://github.com/cfrg/draft-irtf-cfrg-opaque/blob/master/draft-irtf-cfrg-opaque.md#createcredentialresponserequest section it is even referred to as:
```
1. (kU, envU, pkU) = LookupUserRecord(request.id)
```

even though trivial, it might make sense to include id in the CredentialRequest structure definition.

**Comment by kevinlewi** [comment]
See #65 for the prior discussion on the removal of the id parameter from CredentialRequest.

My interpretation of the `LookupUserRecord(request.id)` portion is that it is meant for the wrapper protocol to perform the lookup, so that those details are not kept as part of the OPAQUE protocol.

@chris-wood Thoughts on this / perhaps editing the text to make it more clear that OPAQUE doesn't handle lookup and doesn't manage the id in its CredentialRequest message?

**Comment by chris-wood** [comment]
That referenced line in the text is a bug (it should have been removed). I'm definitely supportive of clarifying the text to make it clear that identity selection and transfer between client and server is not part of OPAQUE's job. @kevinlewi, will you have time to make a PR for this?
