### ISSUE TITLE
rename StoreUserRecord to indicating the finalization instead of optional persistence

### ISSUE THREAD

**Issue by stef** [cfrg/draft-irtf-cfrg-opaque#89]
Just as we dropped the ProtocolMessages part, for the protocol it might be not necessary to call the function StoreUserRecord. For instance my implementation does not care about any kind of persistence or transport of the outcome of the protocol. It might be that the use-case does not need the storage of the user record, for example by just keeping it in memory, or the record might be further processed before storage. Thus i propose to rename the function to `FinalizeUserRecord` instead.

**Comment by chris-wood** [comment]
Good suggestion! Like the wrapping protocol message frames, this also isn't strictly necessary. I'll take a stab at removing this text.

**Comment by stef** [comment]
well actually the function itself is kind of necessary. it adds at least the OPRF key to the record, but possibly also a per-user skS. the result is a record to be stored or persisted or whatever. the point is, that it is not really about storage of the record, but about adding the server secrets to it, that are user-specific.

**Comment by kevinlewi** [comment]
Somewhat unrelated question, but:

Should this specification define a format for the serialized version of the "finalized object" containing (envU, pkS, skS, pkU, kU)? Something like:
```
CredentialRecord {
  opaque envU<1..2^16-1>;
  opaque kU<1..2^16-1>;
  opaque pkU<1..2^16-1>;
}
```

And actually pkS does not need to be stored here, because it is already a part of the credentials object, via:

"Applications MUST include skU in secret_credentials and pkS in either cleartext_credentials or secret_credentials."

And we likely do not want to advocate for storing skS somewhere like this, so we can retain/amend the comment:

"If skS and pkS are used for multiple users, the server can store these values separately and omit them from the user's record."

**Comment by chris-wood** [comment]
Great question, @kevinlewi. Over in HPKE we chose to not specify storage wire formats, since they were primarily an implementation detail. That came back to haunt us when we needed to send serialized HPKE contexts between processes. So my sense is that this might be useful if we anticipate a use case where we would need to move these records around between different OPAQUE implementations. Otherwise, I think we ought to leave it to the wrapper protocol and application.

**Comment by kevinlewi** [comment]
I think it would be something that OPAQUE implementations would have to implement, and not leave to their wrapper protocols, since: what is a wrapper protocol expected to do with envU, kU, pkU other than treat them as raw bytestrings that should be serialized in some format?

So, if its likely the case that OPAQUE protocols will be implementing the serialization in their own manner, I think it would be nice if we define a standard way to organize envU, kU, pkU.

**Comment by chris-wood** [comment]
> what is a wrapper protocol expected to do with envU, kU, pkU other than treat them as raw bytestrings that should be serialized in some format?

If these were serialized and minted by implementation A, then implementation A would presumably know how to parse them. I think this is useful only if, for example, implementation A mints the records and implementation B consumes them. I could see that happening in practice if, e.g., the registration and login phases were two separate processes running different implementations, wherein the registration process minted CredentialRecords and then the login process consumed them. If you think arrangements like this are likely, I see no harm in adding something like CredentialRecord.

As for serialization: yes, we should definitely version them. I'd just stick in the same version used for the protocol version, e.g.:

~~~
struct {
   uint16 version;
   uint16 length;
   select (0xff00) { // version 00 for the draft, or whatever
      // information about the configuration, e.g., OPRF suite and so on, since that determines kU's encoding 
      Envelope envU;
      Scalar kU;
      opaque pkU<0..2^16-1>;
   }
} CredentialRecord
~~~

**Comment by kevinlewi** [comment]
Good points, I see. Yes, I think this scenario could be likely, since registration and login may need to be in different languages (for example).

The struct looks good, except -- why do we need a `uint16 length;` field? Seemingly that could be omitted.

**Comment by chris-wood** [comment]
> The struct looks good, except -- why do we need a uint16 length; field? Seemingly that could be omitted.

Imagine one added support for two versions of OPAQUE at the same time, yet the login only knows how to process one specific version. Since the contents of the record depend on the version, there needs to be a way for implementations that don't support a given version to skip over records they cannot parse, and the length field does just that. So for example, an implementation would read the version field and, if it's unsupported, skip `length` bytes to the next record in a list, and repeat.

**Comment by kevinlewi** [comment]
This would only be a problem if the wrapper protocol stores these records in a contiguous sequence of bytes with no delimiters for the beginnings of each record, though, right?

I don't imagine that this would ever occur... but perhaps I'm missing something. At the very least, these records would be stored as values of a map, or elements of an array.

**Comment by chris-wood** [comment]
Yep, that's true! If a wrapper chose to store these in a map from idU -> [records], then perhaps this would be relevant. If it has some other (simpler) way to delineate different records, we can certainly omit the length. 

@kevinlewi, would you mind proposing a PR for the record format?

**Comment by stef** [comment]
i don't know how the hpke storage formats came to haunt you guys, but i would say that since we do not specify protocol message formats, storage formats also do not need to be specified, or if they do, they might be specified in a different rfc, together with wire formats. the question for me, is is this about the cryptographic protocol or the communication/application protocol, and for me, i prefer to stick to the cryptographic protocol only. since the communication/application protocol brings along a lot of stuff as an low level implementer would nod like to implement.

i am also worried about "variable length" records, that means complexity, i believe the implementation should know exactly how big a record or any protocol message is, without encoding it in the message. implementing parsing of these things means added complexity, and added complexity means attack surface. it is already worrying that `idU` and `idS` might be free-form strings with random lengths - i would really prefer allowing only uuids/hashes or similar fixed-width strings, that would eliminate variable lengths parsing from fixed configuration setups of opaque.

**Comment by kevinlewi** [comment]
Hi @stef, thanks for the comments on this, I think you bring up good points.

I agree that we should stick to only specifying the cryptographic protocol. But, to clarify, aren't we already specifying message / wire formats (e.g. the bytes that consist of a RegistrationRequest) in this RFC? I see this as still being part of the cryptographic protocol. The reason being that we want a wrapper protocol to be able to not have to worry about the internals of the OPAQUE implementation, and if we did not specify the message / wire formats, then it must mean that the wrapper protocol would have to be exposed to the specifics behind kU, rwdU, etc. (which in my opinion is undesirable).

A similar argument I think can be made for why we may want to specify storage formats for the password file. If we do not, then doesn't this mean that the OPAQUE protocol must expose to the wrapper protocol the individual components that make up the password file (pkU, envU, kU), and we would leave it up to the wrapper protocol to decide what to do with these objects? In my opinion, it would feel cleaner to have the OPAQUE protocol dictate how these objects would be serialized together, so that the wrapper protocol need not have to interpret what each of pkU, envU, and kU mean.

> i am also worried about "variable length" records, that means complexity, i believe the implementation should know exactly how big a record or any protocol message is, without encoding it in the message. implementing parsing of these things means added complexity, and added complexity means attack surface.

I agree with this -- I think one way in which we might hope to simplify things would be to consider the suggestions I made in #99 regarding the simplification of the envelope construction. However, this would still mean that we have a "custom identifier" mode, which does not solve the problem of the variable-length `idU` and `idS`. Perhaps we can draft a separate issue to talk specifically about whether or not would be a good idea to enforce fixed-width strings for `idU` and `idS`.

**Comment by stef** [comment]
xposting this here what i commented on the merged change:

> i'm not sure this is a good idea, different use-cases might not need all the bells and whistles. i think i asked in an issue if this is about the standardization of the protocol or it goes beyond that and standardizes also serialization of all kind of wire and storage elements. in implementations using only one instantiation of the protocol the parameters are fixed, and don't need to be stored. if an implementation does not follow the spec and does not store this redundant info in that case, will it still be standards compliant? also some implementations might want to go beyond the currently specified two envelope setups and may want to make all credential extensions configurable, i can see reasons for all configurations. i think there should be a limit of what is part of the standard, and what is free for implementations to decide themselves, and again depending on different configurations of how credential extensions are created this can lead to very different storage formats. my take is to not specify neither the storage format of the record, nor actually the configuration of the envelope. test vectors can still be provided for the protocol, especially if serialization is not fixed, in that case the test vectors can be provided as results of the various steps of the protocol, there is no combinatoric explosion.
