### ISSUE TITLE
Envelope correctness

### ISSUE THREAD

**Issue by chris-wood** [cfrg/draft-irtf-cfrg-opaque#96]
The record sent from client to server during the registration phase is as follows:

~~~
struct {
    Envelope envelope;
    opaque pkU<0..2^16-1>;
} RegistrationUpload;
~~~

As is, the server has no assurance that the private key corresponding to `pkU` is inside (or derived from) the envelope. This raises two questions:

1) Does the client need to prove possession of `skU`?
2) If so, how would this work (non-interactively) for DH-based public keys? If not, we should probably add text clarifying why this isn't needed.

**Comment by kevinlewi** [comment]
Although it would be nice if the client could prove possession of `skU`, I don't think it merits the extra complexity / computation that would be required, since I cannot imagine a scenario in which the server would need the assurance that the private key corresponding to `pkU` is inside the envelope. Did you have an example scenario in mind?

**Comment by chris-wood** [comment]
Nothing comes to mind right now, though I haven't given it much thought.

**Comment by chris-wood** [comment]
Let's close this for now. We can re-open if needed later on.

**Comment by bytemare** [comment]
I don't mean to reopen, but should we mention in the doc that we have thought of this but don't see it as necessary?
